export const defaultValuesOfLead: any = {
  promiseTaken: false,
  mobile_no1: "",
  adhaarNumber: "",
  affordableEmi: "",
  allocateTo: null as null | { label: string; value: string },
  annualIncome: "",
  annualSalesTurnOver: "",
  authSignatoryFName: "",
  authSignatoryLName: "",
  authSignatoryMName: "",
  branch: null as null | { label: string; value: string },
  campaign: null as null | { label: string; value: string },
  cluster: null as null | { label: string; value: string },
  clusterForNI: null as null | { label: string; value: string },
  companyName: "",
  constitution: null as null | { label: string; value: string },
  corpSalaryAcount: "N",
  dateOfIncorparation: "",
  depreciation: "",
  directorSalary: "",
  dob: null as null | Date,
  entityType: null as null | { label: string; value: string },
  firstName: "",
  gender: null as null | { label: string; value: string },
  grossMonthlyIncome: "",
  grossProfit: "",
  industry: null as null | { label: string; value: string },
  industryForNI: null as null | { label: string; value: string },
  interesrPaidOnLoan: "",
  lastName: "",
  listKeyContact: [],
  loanAmount: "",
  maritalStatus: null as null | { label: string; value: string },
  salutation: null as null | { label: string; value: string },
  middleName: "",
  modeOfSalary: "-1",
  monthlyRentalIncome: "",
  nationality: null as null | { label: string; value: string },
  netMonthlyIncome: "",
  netProfitAtTax: "",
  netWorth: "",
  noOfDependents: "",
  occupationType: "",
  otherAnnualIncome: "",
  otherCompanyName: "",
  pan: "",
  purposeOfLoan: null as null | { label: string; value: string },
  queueId: null as null | { label: string; value: string },
  referenceName: "",
  referenceNumber: "",
  scheme: null as null | { label: string; value: string },
  sector: null as null | { label: string; value: string },
  sectorForNI: null as null | { label: string; value: string },
  source: null as null | { label: string; value: string },
  stage: null as null | { label: string; value: string },
  stageForNI: null as null | { label: string; value: string },
  subQueueId: null as null | { label: string; value: string },
  tenure: "",
  typeOfBusiness: null as null | { label: string; value: string },
  typeOfBusinessForNI: null as null | { label: string; value: string },
  addressFlag: "add",
  address: "",
  officeaddress: "",
  city: "",
  landmark: "",
  state: "",
  zipcode: "",
  mailingAddress: "N",
  destinationAddress: "N",
  occupancyStatus: "",
  flatNo: "",
  floorNo: "",
  locality: "",
  mobileArray: [],
  emailArray: [],
  zipcodeId: "",
};

export const listAddress = [
  {
    addressFlag: "add",
    addressId: "1000001058",
    personalDtlId: "1000000566",
    caseId: "",
    addressType: "1000000001",
    address: "",
    officeaddress: "",
    city: "",
    buildingName: "",
    landmark: "",
    state: "",
    zipcode: "",
    email: "",
    stdIsd: "",
    mobile_no1: "",
    mobile_no2: "",
    phone1: "",
    ext1: "",
    ext2: "",
    fax: "",
    std1: "",
    landLine1: "",
    std2: "",
    landLine2: "",
    mailingAddress: "N",
    destinationAddress: "N",
    occupancyMm: "1",
    occupancyYr: "1",
    occupancyStatus: "",
    sameas: "",
    active: "",
    cityName: "",
    bussinessestbyr: "",
    oldaddress: "",
    marketvalue: "",
    gstinno: "",
    currentareaYr: "",
    phone2: "",
    flatNo: "",
    floorNo: "",
    locality: "",
    company_name: "",
    zipcodeId: "",
  },
  {
    addressFlag: "add",
    addressId: "1000001059",
    personalDtlId: "1000000566",
    caseId: "",
    addressType: "1000000002",
    address: "",
    city: "",
    buildingName: "",
    landmark: "",
    state: "",
    zipcode: "",
    email: "",
    stdIsd: "",
    mobile_no1: "",
    mobile_no2: "",
    phone1: "",
    ext1: "",
    ext2: "",
    fax: "",
    std1: "",
    landLine1: "",
    std2: "",
    landLine2: "",
    mailingAddress: "N",
    destinationAddress: "N",
    occupancyMm: "1",
    occupancyYr: "1",
    occupancyStatus: "",
    sameas: "",
    active: "",
    cityName: "",
    bussinessestbyr: "",
    oldaddress: "",
    marketvalue: "",
    gstinno: "",
    currentareaYr: "",
    phone2: "",
    flatNo: "",
    floorNo: "",
    locality: "",
    company_name: "",
    zipcodeId: "",
  },
  {
    addressFlag: "add",
    addressId: "1000001060",
    personalDtlId: "1000000566",
    caseId: "",
    addressType: "1000000003",
    address: "",
    city: "",
    buildingName: "",
    landmark: "",
    state: "",
    zipcode: "",
    email: "",
    stdIsd: "",
    mobile_no1: "",
    mobile_no2: "",
    phone1: "",
    ext1: "",
    ext2: "",
    fax: "",
    std1: "",
    landLine1: "",
    std2: "",
    landLine2: "",
    mailingAddress: "N",
    destinationAddress: "N",
    occupancyMm: "1",
    occupancyYr: "1",
    occupancyStatus: "",
    sameas: "",
    active: "",
    cityName: "",
    bussinessestbyr: "",
    oldaddress: "",
    marketvalue: "",
    gstinno: "",
    currentareaYr: "",
    phone2: "",
    flatNo: "",
    floorNo: "",
    locality: "",
    company_name: "",
    zipcodeId: "",
  },
];
